spring:
  application:
    name: community
  config:
    import: optional:aws-parameterstore:/ktb/community/
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

spring.cloud.aws:
  region:
    static: ap-northeast-2

aws:
  parameterstore:
    enabled: true
    region: ap-northeast-2

jwt:
  secret: ${jwt.secret}

server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,metrics # ALB의 헬스체크를 위해 health, 요청 처리 모니터링하기 위해 metrics

logging:
  level:
    root: WARN
    kr.adapterz: INFO
    org.hibernate.SQL: INFO
  exception-conversion-word: '%ex{short}'
  file:
    path: logs
    name: logs/ktb-community.log